### ISSUE TITLE
[Issue] When trying to generate a component hierarchy, I get an error about max call stack size exceeded

### ISSUE THREAD

**Issue by moiztankiwala-sbits** [CoderAllan/vscode-angulartools#440]
![image](https://github.com/CoderAllan/vscode-angulartools/assets/145761475/a3bc698d-2cb3-454a-8a68-cdfe846ee9ab)

When trying to generate a component hierarchy, I get an error about max call stack size exceeded.

Here is the VS code notification message:
![image](https://github.com/CoderAllan/vscode-angulartools/assets/145761475/90abc0ba-5038-4362-85fe-e8b7c1be0993)
Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

**Comment by CoderAllan** [comment]
A stack overflow is usually caused by some recursive code, but there are no recursive code in the Angular Tools extension. And the error occurred in the webview which indicates an issue with the vis-network Javascript component. 
So I have updated the vis-network component to the latest version and I hope that solves the issue.
Please update to v1.12.0 of the vscode-angulartools extension and see if the update solves the issue.

**Comment by beeing** [comment]
Hi, I'm still facing this error on latest version. Perhaps there's a way for us to filter the input before passing it into vis-network?
