### ISSUE TITLE
Service dependency graph

### ISSUE THREAD

**Issue by natanbr** [CoderAllan/vscode-angulartools#47]
First of all I must say this plugin is awesome.

This is a feature request. 
A very useful feature in my opinion is a dependency injections tree for components and services.
Sorry about my limited drawing skills
![image](https://user-images.githubusercontent.com/2639809/109100735-49eaba00-76da-11eb-8ce4-2bec06c1a196.png)

Thanks!

**Comment by CoderAllan** [comment]
I did not think of that. Good idea. 
Basically what you are asking for is a graph showing what is injected in the constructors of the components and how they related to each other.

I wonder what this command should be called? "Show dependency injection graph"? I will think of something :-)

I will put this on the todo list.
Thanks for the suggestion.

**Comment by natanbr** [comment]
Awesome! 
I was giving some more thought to it perhaps as next phase this diagram can follow the official ["Class Diagram"](https://www.visual-paradigm.com/guide/uml-unified-modeling-language/what-is-class-diagram/) structure. 
It will bring this feature to a new level:
![image](https://user-images.githubusercontent.com/2639809/109198348-f799af80-7752-11eb-8bb2-598619767b6a.png)

I don't know if `vis.js` supports this kind of arrows, but I think there is a room for defining a new official standard for Angular based on the existing UML standards. 
There are few times of relations: 
- Injection (services, modules)
- directive composition (components, directive etc)
- utilities (pipes, helpers etc)
I understand it's beyond the "simple" graph I suggested at first, but if you think it is something you are interested in we can try contact the Angular community to officially standardize the model.

Regarding the name:
Perhaps something like "Generate dependency injection diagram"?

I don't have much experience in extension development, but I think you have an awesome project going on here and I would like to contribute!

**Comment by CoderAllan** [comment]
Hi,

I will have your suggestions in mind when I implement the new graph, but what you are suggesting requires a way more complicated source code parser than what I use at the moment. I did look into using a full-blown parser and found https://github.com/ng-ast/ngast that can parse Angular projects, but it is too slow to give a good user experience in Visual Studio Code.
At the moment what I do is read all *.ts files and then use regular expressions to identify the objects I need in each of the extension commands. This is simple and very fast compared to parsing the entire source code. And this is what I intent to use for generating the dependency injection graph because I can identify the injected classes by regex matching for the constructor pattern.

Best regards
Allan

**Comment by CoderAllan** [comment]
Below is a graph generated by the new command. I will see how I can enrich the graph with some of the suggestions you came up with.
It generated from this repo: https://github.com/gothinkster/angular-realworld-example-app
Let me know what you think.
![DependencyInjectionGraph](https://user-images.githubusercontent.com/11722431/109375400-bb825e00-78bc-11eb-91a5-2e4ba0e03202.png)

**Comment by CoderAllan** [comment]
@natanbr I have now implemented the new graph. It will be available in the marketplace shortly as version 1.6.0.

Thanks for the input.

**Comment by natanbr** [comment]
That looks Awesome! Thanks @CoderAllan! 
I am excited to try it! Will let you know 😁
